apiVersion: v1
kind: Secret
metadata:
  name: game-session-secret
  namespace: game-session
type: Opaque
data:
  # Base64 encoded values - 'gamepass' and 'rootpass'
  DB_PASSWORD: Z2FtZXBhc3M=
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=
  MYSQL_PASSWORD: Z2FtZXBhc3M=
