apiVersion: v1
kind: Service
metadata:
  name: game-session-service
  namespace: game-session
  labels:
    app: game-session-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: game-session-service
